name: "Team Behavior Analysis"
description: "Analyze git history and collaboration patterns"

outputs:
  behavior_score:
    description: "Team behavior score out of 100"
    value: ${{ steps.analysis.outputs.behavior_score }}
  total_commits:
    description: "Total number of commits"
    value: ${{ steps.analysis.outputs.total_commits }}
  total_authors:
    description: "Number of unique authors"
    value: ${{ steps.analysis.outputs.total_authors }}
  message_quality:
    description: "Commit message quality score"
    value: ${{ steps.analysis.outputs.message_quality }}

runs:
  using: "composite"
  steps:
    - name: 👥 Team Collaboration Analysis
      id: analysis
      shell: bash
      run: |
        # Change to workspace root to access git repository
        cd ${{ github.workspace }}

        # Install required dependencies
        npm install --silent @actions/core

        # Run the team behavior analysis script
        node ${{ github.action_path }}/team-behavior.js
