name: "Test Coverage Analysis"
description: "Run tests and calculate coverage metrics"

inputs:
  language:
    description: "Programming language"
    required: true

outputs:
  test_score:
    description: "Test score out of 100"
    value: ${{ steps.test-coverage.outputs.test_score }}
  coverage_percentage:
    description: "Code coverage percentage"
    value: ${{ steps.test-coverage.outputs.coverage_percentage }}
  test_files:
    description: "Number of test files found"
    value: ${{ steps.test-coverage.outputs.test_files }}
  has_tests:
    description: "Whether tests were found"
    value: ${{ steps.test-coverage.outputs.has_tests }}
  coverage_details:
    description: "Detailed coverage analysis"
    value: ${{ steps.test-coverage.outputs.coverage_details }}
  missing_tests:
    description: "Areas missing test coverage"
    value: ${{ steps.test-coverage.outputs.missing_tests }}

runs:
  using: "composite"
  steps:
    - name: 🧪 Run Tests with Coverage
      id: test-coverage
      shell: bash
      env:
        LANGUAGE: ${{ inputs.language }}
      run: |
        # Change to workspace root to access project files and save reports
        cd ${{ github.workspace }}

        # Install required dependencies
        npm install --silent @actions/core

        # Run the test coverage analysis script
        node ${{ github.action_path }}/test-coverage.js
