name: "Security Scan"
description: "Run security vulnerability analysis"

inputs:
  language:
    description: "Programming language"
    required: true

outputs:
  security_score:
    description: "Security score out of 100"
    value: ${{ steps.security-scan.outputs.security_score }}
  high_severity:
    description: "Number of high severity issues"
    value: ${{ steps.security-scan.outputs.high_severity }}
  medium_severity:
    description: "Number of medium severity issues"
    value: ${{ steps.security-scan.outputs.medium_severity }}
  low_severity:
    description: "Number of low severity issues"
    value: ${{ steps.security-scan.outputs.low_severity }}
  security_issues:
    description: "Detailed security issues found (JSON)"
    value: ${{ steps.security-scan.outputs.security_issues }}
  vulnerability_summary:
    description: "Summary of top vulnerabilities"
    value: ${{ steps.security-scan.outputs.vulnerability_summary }}

runs:
  using: "composite"
  steps:
    - name: 🔒 Security Analysis
      id: security-scan
      shell: bash
      env:
        LANGUAGE: ${{ inputs.language }}
      run: |
        # Change to workspace root to access project files and save reports
        cd ${{ github.workspace }}

        # Install required dependencies
        npm install --silent @actions/core

        # Run the security scan script
        node ${{ github.action_path }}/security-scan.js
