name: "Install Dependencies"
description: "Install project dependencies based on detected language"

inputs:
  language:
    description: "Programming language"
    required: true
  framework:
    description: "Framework name"
    required: true

runs:
  using: "composite"
  steps:
    - name: 📦 Install Dependencies
      shell: bash
      run: |
        case "${{ inputs.language }}" in
          "javascript")
            echo "📦 Installing Node.js dependencies..."
            if [ -f "package.json" ]; then
              npm install --production=false || npm install || true
              echo "✅ Node.js $(node --version) | NPM $(npm --version)"
            fi
            ;;
          "python")
            echo "📦 Setting up Python environment..."
            sudo apt-get update -qq
            sudo apt-get install -y python3 python3-pip python3-venv
            if [ -f "requirements.txt" ]; then
              pip3 install -r requirements.txt || true
            fi
            echo "✅ Python $(python3 --version) | Pip $(pip3 --version)"
            ;;
          "go")
            echo "📦 Setting up Go environment..."
            wget -q https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz
            echo "/usr/local/go/bin" >> $GITHUB_PATH
            if [ -f "go.mod" ]; then
              go mod download || true
            fi
            ;;
          *)
            echo "ℹ️ No specific setup required for ${{ inputs.language }}"
            ;;
        esac
