name: "Generate HTML Report"
description: "Generate a beautiful HTML dashboard from hackathon judge results"

inputs:
  team_name:
    description: "Team name for the report"
    required: true
  pr_number:
    description: "Pull request number"
    required: true
  reports_dir:
    description: "Directory containing team reports"
    required: false
    default: "reports/teams"

outputs:
  html_file:
    description: "Path to the generated HTML report file"
    value: ${{ steps.generate-html.outputs.html_file }}

runs:
  using: "composite"
  steps:
    - name: Generate HTML Report
      id: generate-html
      shell: bash
      env:
        TEAM_NAME: ${{ inputs.team_name }}
        PR_NUMBER: ${{ inputs.pr_number }}
        REPORTS_DIR: ${{ inputs.reports_dir }}
      run: |
        echo "🎨 Generating HTML report for team $TEAM_NAME..."

        # Run the HTML generator script
        cd $GITHUB_WORKSPACE
        node .github/scripts/generate-html-report.js "$REPORTS_DIR" "hackathon-report.html"        # Check if the HTML file was created
        if [[ -f "hackathon-report-$TEAM_NAME.html" ]]; then
          echo "✅ HTML report generated successfully"
          echo "html_file=hackathon-report-$TEAM_NAME.html" >> $GITHUB_OUTPUT
          
          # Show file size
          file_size=$(wc -c < "hackathon-report-$TEAM_NAME.html")
          echo "📊 HTML report size: $file_size bytes"
          
          # Check for persistent location as well
          persistent_path="$REPORTS_DIR/$TEAM_NAME/pr-$PR_NUMBER/hackathon-report-$TEAM_NAME.html"
          if [[ -f "$persistent_path" ]]; then
            persistent_size=$(wc -c < "$persistent_path")
            echo "📁 Persistent report also saved: $persistent_path ($persistent_size bytes)"
          fi
          
          # Create a summary
          echo "## 📊 HTML Report Generated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Team:** $TEAM_NAME" >> $GITHUB_STEP_SUMMARY
          echo "- **PR:** #$PR_NUMBER" >> $GITHUB_STEP_SUMMARY
          echo "- **Root File:** hackathon-report-$TEAM_NAME.html" >> $GITHUB_STEP_SUMMARY
          echo "- **Persistent File:** $persistent_path" >> $GITHUB_STEP_SUMMARY
          echo "- **Size:** $file_size bytes" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The HTML report provides a beautiful, interactive dashboard with:" >> $GITHUB_STEP_SUMMARY
          echo "- 📊 Visual score breakdown with color-coded progress bars" >> $GITHUB_STEP_SUMMARY
          echo "- 🔒 Security analysis with detailed vulnerability information" >> $GITHUB_STEP_SUMMARY
          echo "- ⚡ SonarCloud code quality metrics" >> $GITHUB_STEP_SUMMARY
          echo "- 👥 Team collaboration insights" >> $GITHUB_STEP_SUMMARY
          echo "- 🤖 AI attribution analysis" >> $GITHUB_STEP_SUMMARY
          echo "- 🧪 Test coverage information" >> $GITHUB_STEP_SUMMARY
          
        else
          echo "❌ Failed to generate HTML report"
          exit 1
        fi
