name: "Frontend Audit"
description: "Analyze frontend code for usability and accessibility"

inputs:
  framework:
    description: "Frontend framework"
    required: false
    default: "html"

outputs:
  frontend_score:
    description: "Frontend score out of 100"
    value: ${{ steps.audit.outputs.frontend_score }}
  usability_score:
    description: "Usability score"
    value: ${{ steps.audit.outputs.usability_score }}
  accessibility_score:
    description: "Accessibility score"
    value: ${{ steps.audit.outputs.accessibility_score }}
  performance_score:
    description: "Performance score"
    value: ${{ steps.audit.outputs.performance_score }}
  audit_details:
    description: "Detailed audit results"
    value: ${{ steps.audit.outputs.audit_details }}

runs:
  using: "composite"
  steps:
    - name: 🎨 Frontend Usability Analysis
      id: audit
      shell: bash
      env:
        FRAMEWORK: ${{ inputs.framework }}
      run: |
        # Change to workspace root to access project files and save reports
        cd ${{ github.workspace }}

        # Install required dependencies
        npm install --silent @actions/core

        # Run the frontend audit script
        node ${{ github.action_path }}/frontend-audit.js
