name: "Calculate Final Score"
description: "Calculate weighted final score from all analysis components"

inputs:
  test_score:
    description: "Test coverage score"
    required: true
    default: "0"
  sonar_score:
    description: "SonarCloud quality score"
    required: true
    default: "0"
  security_score:
    description: "Security analysis score"
    required: true
    default: "0"
  frontend_score:
    description: "Frontend usability score"
    required: true
    default: "0"
  team_score:
    description: "Team behavior score"
    required: true
    default: "0"
  ai_score:
    description: "AI attribution score"
    required: true
    default: "0"

outputs:
  overall_score:
    description: "Final weighted score out of 100"
    value: ${{ steps.calculate.outputs.overall_score }}
  grade:
    description: "Letter grade (A-F)"
    value: ${{ steps.calculate.outputs.grade }}
  breakdown:
    description: "JSON object with score breakdown"
    value: ${{ steps.calculate.outputs.breakdown }}

runs:
  using: "composite"
  steps:
    - name: "Calculate Weighted Score"
      id: calculate
      shell: bash
      env:
        TEST_SCORE: ${{ inputs.test_score }}
        SONAR_SCORE: ${{ inputs.sonar_score }}
        SECURITY_SCORE: ${{ inputs.security_score }}
        FRONTEND_SCORE: ${{ inputs.frontend_score }}
        TEAM_SCORE: ${{ inputs.team_score }}
        AI_SCORE: ${{ inputs.ai_score }}
      run: |
        # Change to workspace root to save reports
        cd ${{ github.workspace }}

        # Install required dependencies
        npm install --silent @actions/core

        # Run the score calculation script
        node ${{ github.action_path }}/calculate-score.js
