name: "Setup Development Environment"
description: "Setup Node.js, Java, Python and cache dependencies"

inputs:
  node-version:
    description: "Node.js version to setup"
    required: true
    default: "18"
  java-version:
    description: "Java version to setup"
    required: true
    default: "17"
  python-version:
    description: "Python version to setup"
    required: true
    default: "3.x"

runs:
  using: "composite"
  steps:
    - name: ☕ Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: ${{ inputs.java-version }}

    - name: 🚀 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"
        cache-dependency-path: "**/package-lock.json"

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: 📦 Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
