name: "Detect Project Stack"
description: "Detect programming language and framework"

outputs:
  language:
    description: "Detected programming language"
    value: ${{ steps.detect.outputs.language }}
  framework:
    description: "Detected framework"
    value: ${{ steps.detect.outputs.framework }}
  has_frontend:
    description: "Whether project has frontend components"
    value: ${{ steps.detect.outputs.has_frontend }}

runs:
  using: "composite"
  steps:
    - name: 🔍 Analyze Project Structure
      id: detect
      shell: bash
      run: |
        cd ${{ github.action_path }}
        node detect-stack.js
