name: "Post Results Comment"
description: "Post formatted results comment on PR"

inputs:
  overall_score:
    description: "Overall score"
    required: true
  test_score:
    description: "Test score"
    required: true
  sonar_score:
    description: "SonarCloud score"
    required: true
  sonar_url:
    description: "SonarCloud URL"
    required: true
  security_score:
    description: "Security score"
    required: true
  frontend_score:
    description: "Frontend score"
    required: true
  team_score:
    description: "Team score"
    required: true
  ai_score:
    description: "AI score"
    required: true
  detected_stack:
    description: "Detected technology stack"
    required: true
  pr_number:
    description: "PR number"
    required: true
  team_name:
    description: "Team name"
    required: true
  high_severity:
    description: "Number of high severity security vulnerabilities"
    required: false
    default: "0"
  medium_severity:
    description: "Number of medium severity security vulnerabilities"
    required: false
    default: "0"
  low_severity:
    description: "Number of low severity security vulnerabilities"
    required: false
    default: "0"
  coverage_percentage:
    description: "Test coverage percentage"
    required: false
    default: "0"
  test_files:
    description: "Number of test files"
    required: false
    default: "0"
  sonar_status:
    description: "SonarCloud quality gate status"
    required: false
    default: "UNKNOWN"
  code_smells:
    description: "Number of code smells"
    required: false
    default: "0"
  bugs:
    description: "Number of bugs"
    required: false
    default: "0"
  vulnerabilities:
    description: "Number of vulnerabilities from SonarCloud"
    required: false
    default: "0"
  sonar_analysis_results:
    description: "Detailed SonarCloud analysis results JSON"
    required: false
    default: "{}"
  reports_committed:
    description: "Whether persistent reports were committed to the repository"
    required: false
    default: "false"
  report_url:
    description: "URL to the persistent analysis report in the repository"
    required: false
    default: ""
  html_report_file:
    description: "Path to the generated HTML report file"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: 📥 Download Analysis Artifacts
      uses: actions/download-artifact@v4
      with:
        name: hackathon-analysis-${{ inputs.team_name }}-pr${{ inputs.pr_number }}
        path: ./analysis-results/

    - name: 💬 Post Analysis Results
      shell: bash
      env:
        OVERALL_SCORE: ${{ inputs.overall_score }}
        TEST_SCORE: ${{ inputs.test_score }}
        SONAR_SCORE: ${{ inputs.sonar_score }}
        SECURITY_SCORE: ${{ inputs.security_score }}
        FRONTEND_SCORE: ${{ inputs.frontend_score }}
        TEAM_SCORE: ${{ inputs.team_score }}
        AI_SCORE: ${{ inputs.ai_score }}
        HIGH_SEVERITY: ${{ inputs.high_severity }}
        MEDIUM_SEVERITY: ${{ inputs.medium_severity }}
        LOW_SEVERITY: ${{ inputs.low_severity }}
        COVERAGE_PERCENTAGE: ${{ inputs.coverage_percentage }}
        TEST_FILES: ${{ inputs.test_files }}
        SONAR_STATUS: ${{ inputs.sonar_status }}
        CODE_SMELLS: ${{ inputs.code_smells }}
        BUGS: ${{ inputs.bugs }}
        VULNERABILITIES: ${{ inputs.vulnerabilities }}
        TEAM_NAME: ${{ inputs.team_name }}
        DETECTED_STACK: ${{ inputs.detected_stack }}
        SONAR_URL: ${{ inputs.sonar_url }}
        PR_NUMBER: ${{ inputs.pr_number }}
        SONAR_ANALYSIS_RESULTS: ${{ inputs.sonar_analysis_results }}
        REPORTS_COMMITTED: ${{ inputs.reports_committed }}
        REPORT_URL: ${{ inputs.report_url }}
        HTML_REPORT_FILE: ${{ inputs.html_report_file }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: |
        cd ${{ github.action_path }}

        # Install required dependencies
        npm install --silent @actions/github @actions/core

        # Run the JavaScript script
        node post-comment.js
