name: "AI Usage Detection"
description: "Detect and analyze AI-generated code patterns"

outputs:
  ai_score:
    description: "AI attribution score out of 100"
    value: ${{ steps.ai-analysis.outputs.ai_score }}
  ai_percentage:
    description: "Estimated percentage of AI-generated content"
    value: ${{ steps.ai-analysis.outputs.ai_percentage }}
  has_attribution:
    description: "Whether AI usage is properly attributed"
    value: ${{ steps.ai-analysis.outputs.has_attribution }}

runs:
  using: "composite"
  steps:
    - name: 🤖 AI Usage Analysis
      id: ai-analysis
      shell: bash
      run: |
        cd ${{ github.action_path }}

        # Install required dependencies
        npm install --silent @actions/core

        # Run the AI detection analysis script
        node ${{ github.action_path }}/ai-detection.js
